services:
  - type: web
    name: maverick-challenge-ai-health
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn aihealth.wsgi:application"
    envVarGroups:
      - name: ai-health-secrets
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG 
        value: False